### ISSUE TITLE
[Mod compat] liroth armor sets

### ISSUE THREAD

**Issue by Surpos0** [xanthian/expert_armor#10]
there are two materials ruby and lirothian
https://www.curseforge.com/minecraft/mc-mods/liroth-revamped-fabric

**Comment by xanthian** [comment]
There are a lot more materials from what I can see, are these not active?
I'll add support for them regardless, if they need changing as Liroth updates then i'll fix it.

**Comment by Surpos0** [comment]
Thx a lot.
