### ISSUE TITLE
Incompatability with Create: Diving Gear requires copper plate

### ISSUE THREAD

**Issue by LeakingAmps** [xanthian/expert_armor#11]
I have a smallish modlist, and I cannot make Diving Gear, because it requires Copper Armor Plate because of this mod, and Copper Armor Plate has no recipe. Please add a recipe for Copper Armor Plate, or don't add it to other mods' recipes.

1.19.2
AppleSkin
Architectury
Backpack Mod
Bad Packets
The Bumblezone - Fabric
Cardinal Components API
Chef's Delight
Cloth Config V8
Continuity
CorgiLib
Create
Data Attributes
Debugify
EMI
EmiCompat
Enhanced Celestials
Expanded Delight
Expert_Armor
Fabric API
Farmer's Delight
GeckoLib
Gravestones
Guard Villagers Fabric
Handcrafted
Indium
Iris
Iron Bows (Fabric)
Lithium
MidnightLib
Mimic
Mob Variants
Mod Menu
More Axolotl Variants API
More Axolotl Variants Mod
Nameplate
NBT Crafting
Offline Player Cache
Phosphor
PlayerEX
Rat's Mischief
RPG Difficulty
Sodium
Spice of Fabric
Trinkets
WTHIT
YetAnotherConfigLib

**Comment by xanthian** [comment]
Which mod adds diving gear?

edit..
sorry.. i should learn to read.
checking it out now.

**Comment by xanthian** [comment]
got it, mistake in the json for the copper plate recipe
will upload tomorrow, apologies.

**Comment by LeakingAmps** [comment]
Thank you very much!

**Comment by masuibass** [comment]
@xanthian It is still an issue. Copper armor plate cannot be created. Could you fix it?

**Comment by xanthian** [comment]
will be fix in 2.5 
uploading to CF as I type this..
