### ISSUE TITLE
Textures not loaded for Mythic Metals compatibility, possible texture mod incompatibility

### ISSUE THREAD

**Issue by ShotCosine** [xanthian/expert_armor#3]
Textures aren't being loaded for the Mythic Metals armor plates:

![Screenshot (2)](https://user-images.githubusercontent.com/50850656/154385262-6c1c402e-46bc-445b-95cb-22bd1a1b0c1a.png)
.
Log: **(At 19:45:02 the error is detected)**

[latest.log](https://github.com/xanthian/expert_armor/files/8084765/latest.log)

As you can see, I have a ton of mods, some of which are for adding optifine texture compatibility like Continuity, CEM, and CIT Resewn. Could be an issue from those.

**Comment by ShotCosine** [comment]
Looking at the log it seems like the mod is loading the textures, but for some reason the model jsons aren't being accepted

**Comment by xanthian** [comment]
looks like something is messing with what type of json is expected. but I think I have a fix.
https://www.curseforge.com/minecraft/mc-mods/expert-armor/files/3650680

**Comment by ShotCosine** [comment]
Can confirm that it is working! Quick fix and excellent mod support!
