### ISSUE TITLE
Modified Recipes Aren't Present in Mods Listed as Compatible

### ISSUE THREAD

**Issue by TheGreenNickel** [xanthian/expert_armor#5]
I've been working on a modpack for a series, and it includes this mod. I also happen to be using Mythic Metals, Dragon Loot and Advanced Netherite, all of which are listed as being compatible with Expert Armor. However, when I enter a world, the recipes are still the same as normal, instead of the modified ones created by this mod. The metal plates are still available as items, which means that the mods are working together to an extent, but the recipes themselves are still all ingots.
![image](https://user-images.githubusercontent.com/104462717/165382228-6bdec318-6071-4681-a49d-9b36808f379b.png)
![image](https://user-images.githubusercontent.com/104462717/165382387-7286ba82-771f-4b33-837b-13d99fb0e007.png)
When I was first using the mod in my pack, it was working, but it stopped after that. I then undid every mod install I've made since adding Expert Armor, but it's still giving me the all-ingot recipes.

**Comment by xanthian** [comment]
Could you list the mods + versions you are using

**Comment by TheGreenNickel** [comment]
> Could you list the mods + versions you are using

Yeah. It's a long list, so I didn't add it to the original thread, but here:

- Advanced Netherite 1.4.1-1.18.2
- Alloy Forgery 2.0.9+1.18
- Amplified Nether 1.0.1
- Architectury API 3.7.26
- Cloth Config 6.2.57
- Collective 1.18.x-4.9
- Comforts 1.0.3-1.18.1
- Craftable Horse Armour & Saddle 1.18-1.8
- Distant Horizons 1.6.2a-1.18.1
- Dragon Loot 1.0.10
- Expert Armor 1.7.5
- Extended Armor Bars 1.1.0
- Extra Origins 1.18-9
- Fabric API 0.46.6+1.18
- Fabric Enchantments 0.7.0
- Feature NBT Deadlock Be Gone 1.0.1+1.18.1
- Global Data & Resource Packs 1.18.1-1.11.3 (used with the Better Dungeons, Better Strongholds, and More Villagers compatibility data packs for the Repurposed Structures mod)
- Goat Origins (Rammling) v1.2
- Mob Origins 1.8.0
- More Villagers 1.18.1-3.1.1
- Mythic Metals 0.12.2
- No Null Processors 2.0.1+1.18.1
- Nullscape 1.1
- Origins 1.18-1.3.1
- Origins: Classes 1.18-1.2.4
- Origins: Umbrellas 1.5.1
- Pehkui 3.1.0+1.14.4-1.18.1
- Repurposed Structures 3.3.12+1.18.1
- Roughly Enough Items 7.3.443
- Sky Villages 1.0.1-1.18.1
- Sodium mc1.18.1-0.4.0-alpha6+build.14
- Spellbound Enchantments 1.7.2
- Terralith 2.0.12
- Towers of the Wild: Additions 1.1.0-1.18.1
- Towers of the Wild: Reworked 2.2.0
- Village Spawn Point 1.18.x-1.8
- Wandering Collector 1.1.1+mc1.18.1
- When Dungeons Arise 1.18.1-2.1.49d-beta
- Xtra Arrows MC1.18.2+v1.8.1
- YUNG'S API 1.18-fabric-36
- YUNG'S Better Dungeons 1.18-1.0
- YUNG'S Better Mineshafts 1.18.1-1.0
- YUNG'S Better Strongholds 1.18.1-1.0.1

These mods were all loaded on Fabric Loader 0.13.3-1.18.1.

**Comment by xanthian** [comment]
ok, thanks
i'll try replicate it and report back asap

**Comment by xanthian** [comment]
Its an error to do with load order.
When I load my test world I get this
_Reloading ResourceManager: Default, Fabric Mods (Alloy Forgery, DragonLoot, Expert_Armor, Fabric Tool Attribute API (v1), Mythic Metals), **minecraft/eamodcompat**_

When I load a new world it does this
_Reloading ResourceManager: Default, **minecraft/eamodcompat**, Fabric Mods (Alloy Forgery, DragonLoot, Expert_Armor, Fabric Tool Attribute API (v1), Mythic Metals)_

Notice **eamodcompat** is last on my test world.
I created a new save on my test install and it incorrectly loads it early, im surprised nobody else has raised this!

Investigating as to why the load order has suddenly broken/changed as resource packs should always be last.

**Comment by Z-S117** [comment]
Is this issue still being worked on? I'm having the same experience with all mods that are currently included on the curse forge page under 'optional dependencies'

**Comment by xanthian** [comment]
1.18 no longer supported.
tested working fine in 1.19

mods are required on both server & client for it to function as intended.
