### ISSUE TITLE
MythicMetals has new armor and therefore no plate

### ISSUE THREAD

**Issue by Laifsyn** [xanthian/expert_armor#6]
Confirmed(by myself): Steel armor.
Link to changelog: https://www.curseforge.com/minecraft/mc-mods/mythicmetals/files/3853345
![image](https://user-images.githubusercontent.com/99366187/177051899-0c77fccb-48e0-4037-9ef6-1dd634c7b0f1.png)

**Comment by xanthian** [comment]
Added in 1.19 version
