### ISSUE TITLE
[Compat Req] Gobber armor

### ISSUE THREAD

**Issue by elhertz** [xanthian/expert_armor#8]
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric

**Comment by xanthian** [comment]
Already has it???

**Comment by elhertz** [comment]
Oh I'm sorry! I checked if it was already requested on github issues cause I didn't see a list of compatible mods on curseforge. I don't usually read changelogs, that's my fault. Sorry again!

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/183745373-8875550d-ea24-4fa4-8ee6-43d5a0bfbe4f.png)
